<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Evan Minton</Authors>
    <Product>TCNet</Product>
    <Version>3.0.0</Version>
    <Copyright>Copyright © Evan Minton. TCNet Link Specification © Event Imagineering Group.</Copyright>
  </PropertyGroup>
</Project>
